apiVersion : apps/v1
kind: Deployment
metadata:
  name: cartreact 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartreact
  template:
    metadata:
      labels:
        app: cartreact 
    spec:
      containers:
        - name: cartreact 
          image: crikea.azurecr.io/cartreact
          ports:
          - containerPort: 80